### ISSUE TITLE
CircularProgressBar might not compatible to our apps

### ISSUE THREAD

**Issue by nqta0611** [TinkersStudio/MusicCloud#16]
I have not gone in deep yet. But look like the current resource of CircularProgressBar we are planning to use is just simple display the progress, might not function as a seek bar. 

Need more research on this

[https://github.com/devadvance/circularseekbar](url)
[https://github.com/RaghavSood/AndroidCircularSeekBar](url)
[https://github.com/neild001/SeekArc](url)

**Comment by dungquoctrinh** [comment]
We can pushed this one back as the last item to implement if needed

**Comment by dungquoctrinh** [comment]
Yep. This one doesn't have seek bar
