### ISSUE TITLE
Music notification bar

### ISSUE THREAD

**Issue by dungquoctrinh** [TinkersStudio/MusicCloud#6]
- Learn and setup music notification bar

**Comment by nqta0611** [comment]
Able to put the customize MyNotification Bar up already, need enhancement to make it easy to set info on the notification bar

**Comment by dungquoctrinh** [comment]
Need testing on this since the fragment is in place

**Comment by dungquoctrinh** [comment]
Fix the foreground issues

**Comment by dungquoctrinh** [comment]
Add custom layout: http://www.tutorialsface.com/2015/08/android-custom-notification-tutorial/ @nqta0611

**Comment by nqta0611** [comment]
Done
